CREATE DATABASE NETFLIX
GO

USE NETFLIX
GO

CREATE TABLE ViewingActivity(
	PROFILE_NAME VARCHAR(100),
	START_TIME DATETIME,
	DURATION TIME,
	ATTRIBUTES VARCHAR(100),
	TITLE VARCHAR(100),
	SUPPLEMENTAL_VIDEO_TYPE VARCHAR(100),
	DEVICE_TYPE VARCHAR(100),
	BOOKMARK TIME,
	LATEST_BOOKMARK TIME,
	COUNTRY VARCHAR(100)
)
GO


BULK INSERT ViewingActivity
FROM 'C:\Users\Admin\Documents\Alan\BI\POWER BI\PROJETOS\Projeto 2 - Netflix\Dados\CONTENT_INTERACTION\ArquivoImportar.csv'
WITH( CODEPAGE = '65001',
		KEEPIDENTITY,
		FIRSTROW = 2,
		FIELDTERMINATOR = ';',
		ROWTERMINATOR = '0x0a');
GO

