CREATE DATABASE FINANCEIRO
GO

USE FINANCEIRO
GO

CREATE TABLE DRE(
	CODIGO INT IDENTITY UNIQUE NOT NULL,
	ESTRUTURA VARCHAR(100) UNIQUE NOT NULL,
	DESCRICAO VARCHAR(100) NOT NULL,
	TIPOMOVIMENTO VARCHAR(100) NOT NULL,
	LANCAMENTOS BINARY NOT NULL,
	CALCULADA BINARY NOT NULL,
	COMPETENCIA VARCHAR(100) NOT NULL,
	CHECK (TIPOMOVIMENTO IN('ENTRADA', 'SAIDA', 'AMBOS')),
	CHECK (COMPETENCIA IN('DATA DE VENCIMENTO', 'DATA DA EMISSAO', 'DATA DO PAGAMENTO'))
)
GO

-- ADICIONANDO PRIMARY KEY NOMEADA
ALTER TABLE DRE
ADD CONSTRAINT PK_CODIGO_DRE
PRIMARY KEY(CODIGO)

-- ALTERANDO TIPO DE DADOS
ALTER TABLE DRE
ALTER COLUMN LANCAMENTOS VARCHAR(100) NOT NULL
GO

ALTER TABLE DRE
ALTER COLUMN CALCULADA VARCHAR(100) NOT NULL
GO

-- ADICIONANDO CHECK 
ALTER TABLE DRE
ADD CHECK (LANCAMENTOS IN('VERDADEIRO', 'FALSO'))
GO

ALTER TABLE DRE
ADD CHECK (CALCULADA IN('VERDADEIRO', 'FALSO'))
GO

-- IMPORTANDO DADOS - codificação ANSI
BULK INSERT DRE
FROM 'C:\Users\Admin\Documents\Alan\BI\POWER BI\PROJETOS\Projeto 4 - DRE\DRE Estrutura.csv'
WITH (
	FIRSTROW = 2,
	KEEPIDENTITY,
	CODEPAGE = '1252',
	FIELDTERMINATOR = ';',
	ROWTERMINATOR = '0x0a'
);
GO
